language: node_js
node_js:
  - 12.7.0
install:
  - npm install
  - npm install -g vsce
stages:
  - build
  - package
jobs:
  include:
    - stage: build
      name: Build
      script: npm run compile
    - stage: package
      name: Package
      script: vsce package
before_deploy:
  - echo "deploying to github release"
deploy:
  provider: releases
  api_key:
    secure: mM+7qNt8eBpB4fNGAzRdu2ZAKBDpMibRJjIWqH3WhyUsdLAt6nYHgCgCwj+Q2FYQ1tIXqqroRX416zYEeqpshN1nyyF0Ia0JcvG7ft9NsiVLs+zDHOEx+SS8qEwwW+YNESXMo5JKoRuY1O8VEQwdELk4xOfbRB9lr8mP02QGtZKlUkGChawQL3g9IQFXn8eYS0YKlU+tN8fobIB/Sra2MKQR0Bz4Gs0cN5HNYF+A/RUrQRZx8iLjIpwtFyHuJhUWSj4Prxk5jaXOIUh2oFBpBMyXOeZBg+1jam1wSsu+T+pH6SvqJIUpsSfZ9eT4jXOTCDqhESeQTaLKJtACYiWZxjOiyr5MvFNYsnYqvoJnyxTewg1eSuSK7g4p16wANFmUts+f5Z+g1U5BHfr9PWkERIGW5iGe2d9gi+M+XQnT10A32Z4GLH8yPX8Jvz4SY2Lf2Pftxr/qrFv0cFywpXHkVUmnRV/g6CTQ8kzNMMcb7az9CDyU/AE7fsQByMXDlTA033Zl7D2h7cyCPIt96Ivf3/7vhJ1bVGMbhUJnnFifH/fDTgdzhACyhaIVD+gYEwHlwbYAsyJJMeqM370tmkIz49fyfDClAYOJp1FRArZBRqsvS+jhfJ6TQRg9XmEdZXR3rIppeyl03Z4me+90b9HhRtqSP+1iTRBdUs+QAVpigHY=
  file_glob: true
  file: vscode-auto-complete-*
  skip_cleanup: true
  on:
    tags: true
